### ISSUE TITLE
Make sure extension CSS applies only to extension output

### ISSUE THREAD

**Issue by nsd0sproffe** [nitsan-technologies/ns_timeline#6]
Hi nitsan team,

we are experiencing some annoying, intrusive behavior of your CSS in our TYPO3 installation, especially coming from 
https://github.com/nitsan-technologies/ns_timeline/blob/2a61cab8d80f123439398641dbc7270afdfa0fe0/Resources/Public/css/default.min.css#L1

Please make sure your CSS formats applies only to the extension output, i.e. div.ns-timeline and ancestors. Any general formats, like setting up the box-model for the entire document or creating generic color classes like "blue" etc., should use appropriate cascading selectors. And please check your other CSS files, too! ;-)

We're using the premium version of ns_timeline 12.1.0 iwth TYPO3 12.4

Thank you in advance and regards
Sven

**Comment by nitsan-technologies** [comment]
Hey @tastendruecker 

Thank you for reaching out and share your valuable feedback.

We have thoroughly reviewed the issue you mentioned in the `EXT:ns_timeline/Resources/Public/css/default.min.css` file, as well as other related CSS files. The issue has been resolved, and we have released version 12.1.3 of the ns_timeline extension.

Please update to the latest version and let us know if you have any other feedback and queries.

Cheers, Team NITSAN

**Comment by nsd0sproffe** [comment]
Hey @nitsan-technologies team,

thanks for your quick response! Could you update the premium version, too? Currently, the latest version seems to be 12.1.1. Or am I missing something?

Cheers!

**Comment by nitsan-technologies** [comment]
Hey @tastendruecker 

Thanks for sharing your kind words.

Yes, we have already released in premium version too. We have also take a test drive with the latest version v12.1.3
See attached screenshot <img width="1863" alt="image" src="https://github.com/user-attachments/assets/4dde47c3-fce0-4599-84e1-df7099a016b6">

Please navigate to the License Manager and check for updates. If you are in composer, make sure to composer clear cache.

If you're unable to update to the premium version, kindly share backend access so we can assist further.

Cheers, Team NITSAN

**Comment by nsd0sproffe** [comment]
Works now after upgrading ns-license to new major version 13 :-)

Thanks and cheers!

**Comment by nitsan-technologies** [comment]
Hey @tastendruecker 

Great to hear that it’s working now after upgrading to the new major version 13! If you need any further assistance or have questions down the line, feel free to reach out.

Thanks, and cheers!
