### ISSUE TITLE
BUG: CSS Rule "Hide the overflow in IE" breaks styling

### ISSUE THREAD

**Issue by bh-teufels** [nitsan-technologies/ns_timeline#7]
```
/**
 * Hide the overflow in IE.
 */
_:not(:root) {
  overflow: hidden;
}
```
(reset.css in line 238)

this global css styling rule breaks complete website styling after updating to ns_timeline 12.1.1 (from 12.1.0)

**Comment by nitsan-technologies** [comment]
Hey @bh-teufels 

We apologize for any inconvenience caused. We are pleased to inform you that we have recently released a minor bug-fix version, V12.1.2. Kindly proceed with the update at your convenience.

Should you encounter any further issues, please do not hesitate to reach out to us.

Cheers, Team NITSAN
